### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by matipoirierg** [RenardNocturne/Discord-SelfBot-Spam-Pub#1]
make it possible to send messages inside the new threads feature
![Screenshot 2023-03-31 003544](https://user-images.githubusercontent.com/97362850/229016503-de6439e2-fb98-49d7-8efa-8548860a436e.png)

**Comment by RenardNocturne** [comment]
Yep I'll try my best but it might take a while !

**Comment by RenardNocturne** [comment]
Its done ! It should work fine 👌 However if you notice something wrong, please reach me !
