### ISSUE TITLE
le spammer reste bloqué sans rien faire après s'être connecté au compte

### ISSUE THREAD

**Issue by vaaaaaaaal** [RenardNocturne/Discord-SelfBot-Spam-Pub#2]
![image](https://github.com/RenardNocturne/Discord-SelfBot-Spam-Pub/assets/116454085/8ea1a4d7-23de-4fb3-97a4-6e7488ed7dbc)

**Comment by RenardNocturne** [comment]
Bonjour as-tu attendu au moins dix minutes ou as-tu directement éteint la console en voyant que le bot n'envoyait pas le message ?

Le bot attends un temps aléatoire (entre 0 et 10 minutes par défaut) avant d'envoyer les pubs pour se faire passer pour un humain, peut-être n'as tu pas attendu assez longtemps ? 
Tu peux modifier ce paramètre ici : https://github.com/RenardNocturne/Discord-SelfBot-Spam-Pub/blob/master/Events/Ads/spamAds.js
et là : https://github.com/RenardNocturne/Discord-SelfBot-Spam-Pub/blob/master/Events/Client/ready.js (à la toute fin, dans la fonction `client.pickRandomNumberBetweenTwoNumbers(0, 10)`

Si ce n'est toujours pas bon, n'hésites pas à me le faire savoir :)
