### ISSUE TITLE
Bot logs in successfully but doesn't send any messages to the selected channel. 

### ISSUE THREAD

**Issue by M1dul** [RenardNocturne/Discord-SelfBot-Spam-Pub#3]
After edition config.js file and putting my token, message, channel id there. When I run the bot it runs but doesn't send any messages to channel. It did send the message once the first time . But after that it didnt send any messages at all. 
Also can tell me where can i add/set the time delay ? Will appreciate it a lot if you give the delay instructions in Readme file :D 
Also Can i have your discord? So I can talk to you directly

**Comment by RenardNocturne** [comment]
Hi, I'm sorry to hear that you are encountering an issue with this project, feel free to slide in my DMs, my discord: renardnocturne
I'm kinda busy right now, i'll try to search for a solution tomorrow :)
About the delay, you can change it right here: https://github.com/RenardNocturne/Discord-SelfBot-Spam-Pub/blob/master/Events/Ads/spamAds.js (the same link is in the Readme, just under the line about issues).

**Comment by M1dul** [comment]
I have added you in discord

**Comment by RenardNocturne** [comment]
Was a delay issue, then led to the creation of Deploying-Online branch
